project:
  type: website

website:
  title: "Supercharge your research"  
  page-navigation: true
  site-url: https://jules32.quarto.pub/
  repo-url: https://github.com/openscapes/supercharge-your-research/
  repo-actions: [edit, source, issue]

format:
  html:
    theme: cosmo
    toc: true